# Homepage — Bookmarks / Shortcuts
# Docs: https://gethomepage.dev/configs/bookmarks/

- Administration & Network:
    - Router Admin:
        - icon: router.png
          href: http://192.168.1.1
    - GitHub Repo:
        - icon: github.png
          href: https://github.com/salvadorcampanella/homelab-E580
    - DuckDNS:
        - icon: duckdns.png
          href: https://www.duckdns.org/
    - Speedtest:
        - icon: speedtest-tracker.png
          href: https://www.speedtest.net/

- Documentation & Utilities:
    - Homepage Docs:
        - icon: homepage.png
          href: https://gethomepage.dev/
    - Servarr Wiki:
        - icon: radarr.png
          href: https://wiki.servarr.com/
